<a href="https://colab.research.google.com/github/Aubin-dev/Tensorflow/blob/main/Apprentissage_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import tensorflow as tf

In [ ]:
# define a matrix and a vector
matrix = tf.constant([[1., 1.], [2., 3.]])
vector = tf.constant([[4.], [5.]])

# define the operation we want to perform
matvec = tf.matmul(matrix, vector)
avg = tf.reduce_mean(matvec)

with tf.compat.v1.Session() as sess:
  output = sess.run(matvec)
  print(output)

[[ 9.]
 [23.]]


In [ ]:
avg = tf.reduce_mean(matvec)
with tf.compat.v1.Session() as sess:
  out= sess.run(avg)
  print(out)

16.0


In [ ]:
# define a matrix and a vector
matrix = tf.constant([[1., 1.], [2., 3.]], name="matrix")
vector = tf.constant([[4.], [5.]], name="vector")

# define the operations 
matvec = tf.matmul(matrix, vector, name="mult")
avg = tf.reduce_mean(matvec, name="mean")

# create a session (automatically closed)
with tf.compat.v1.Session() as sess:

	# write graph to disk
	writer =tf.compat.v1.summary.FileWriter("example", sess.graph)
	# execute the operation and get the result
	output = sess.run(avg)

	# print the result
	print(output)


16.0


In [ ]:
# define a matrix and a vector
matrix = tf.constant([[1., 1.], [2., 3.]], name="matrix")
vector = tf.constant([[4.], [5.]], name="vector")

# define the operations 
matvec = tf.matmul(matrix, vector, name="mult")
avg = tf.reduce_mean(matvec, name="mean")

# create a session (automatically closed)
with tf.compat.v1.Session() as sess:

	# write graph to disk
	writer = tf.compat.v1.summary.FileWriter('example', sess.graph)

	# execute the operation and get the result
	output1, output2 = sess.run([matvec,avg])

	# print the result
	print(output1)
	print(output2)



[[ 9.]
 [23.]]
16.0


In [ ]:
# a list of 3 vectors (actually each vector is a 2x1 matrix)
O = [[[2.3],[1.1]], [[-6.],[-3.4]], [[4.],[1.]]]

matrix = tf.constant([[1., 1.], [2., 3.]])
offset = tf.compat.v1.placeholder(tf.float32, shape=(2,1))
vector = tf.Variable([[4.], [5.]])

matvec = tf.matmul(matrix, vector) 
vector_with_offset = tf.add(vector, offset)
updated_vector = tf.compat.v1.assign(vector, vector_with_offset) 

with tf.compat.v1.Session() as sess:
	sess.run(tf.compat.v1.global_variables_initializer())

	for i in range(0, len(O)):

		# updating the value of vector, 
		# using the i-th vector of O as offset
		sess.run(updated_vector, feed_dict={offset: O[i]})

		# running the multiplication (and evaluating vector)
		output1, output2 = sess.run([vector, matvec])

		print("* Offset: " + str(O[i]))
		print(output1)
		print(output2)


* Offset: [[2.3], [1.1]]
[[6.3]
 [6.1]]
[[12.4]
 [30.9]]
* Offset: [[-6.0], [-3.4]]
[[0.3000002]
 [2.6999998]]
[[3. ]
 [8.7]]
* Offset: [[4.0], [1.0]]
[[4.3      ]
 [3.6999998]]
[[ 8. ]
 [19.7]]
